import test from 'node:test';import assert from 'node:assert/strict';
import {GameAuthority} from './worker.mjs';
const origin='https://lombrix-test.example';
function context(data=new Map()) {let alarm=null;return {data,storage:{async list({prefix}){return new Map([...data].filter(([k])=>k.startsWith(prefix)).map(([k,v])=>[k,structuredClone(v)]));},async put(k,v){data.set(k,structuredClone(v));},async delete(k){data.delete(k);},async getAlarm(){return alarm;},async setAlarm(n){alarm=n;}},blockConcurrencyWhile(fn){return fn();}};}
function client(actor){return {cookies:new Map(),seq:Date.now(),async req(path,body){const headers={'Cookie':[...this.cookies].map(([k,v])=>k+'='+v).join('; ')};if(body!==undefined){headers['Content-Type']='application/json';headers.Origin=origin;}
 const res=await actor.fetch(new Request(origin+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body)}));
 const set=res.headers.get('set-cookie');if(set){const pair=set.split(';')[0],i=pair.indexOf('=');this.cookies.set(pair.slice(0,i),pair.slice(i+1));}
 return {status:res.status,data:await res.json(),headers:res.headers};}};}
async function match(count=2,kind='duel'){const ctx=context(),actor=new GameAuthority(ctx,{}),players=Array.from({length:count},()=>client(actor));
 const made=await players[0].req('/api/rooms',{name:'Alice',kind,capacity:count,options:{worms:2,theme:'sakura',turnSeconds:30,seed:31415}});assert.equal(made.status,201);const root='/api/rooms/'+made.data.room.code;
 for(let i=1;i<count;i++){assert.equal((await players[i].req(root+'/join',{name:'Invité '+i})).status,200);assert.equal((await players[i].req(root+'/ready',{ready:true})).status,200);}
 for(const p of players)await p.req(root+'/sync');assert.equal((await players[0].req(root+'/start',{})).status,200);for(const p of players)await p.req(root+'/sync');return {ctx,actor,players,root};}
test('public Fetch authority: two guests, shared terrain, secure cookie, no opponent command',async()=>{const {actor,players,root}=await match();const [a,b]=await Promise.all(players.map(p=>p.req(root+'/sync')));assert.equal(a.data.game.seed,b.data.game.seed);assert.equal(a.data.game.key,b.data.game.key);assert.equal(a.data.game.worms.length,4);assert.equal(a.data.room.you===b.data.room.you,false);const active=a.data.game.team,idx=a.data.room.myTeam===active?0:1,other=1-idx;
 const command={matchId:a.data.game.key,turn:a.data.game.turn,seq:++players[idx].seq,command:{type:'fire',weapon:'rocket',angle:-.4,power:.55}};
 const bad=await players[other].req(root+'/action',{...command,seq:++players[other].seq});assert.equal(bad.status,409);
 const ok=await players[idx].req(root+'/action',command);assert.equal(ok.status,200);assert.equal((await players[idx].req(root+'/action',command)).status,409);
 const packet=await players[other].req(root+'/sync');assert.equal(packet.data.game.phase,'flight');assert.ok(packet.data.game.events.some(e=>e.type==='fire'));assert.ok(actor.app.rooms.size===1);
});
test('durable room restoration preserves membership and match',async()=>{const {ctx,actor,players,root}=await match();const initial=(await players[0].req(root+'/sync')).data;await actor.persist();const restored=new GameAuthority(context(ctx.data),{}),p=client(restored);p.cookies=players[0].cookies;const result=await p.req(root+'/sync');assert.equal(result.status,200);assert.equal(result.data.room.you,initial.room.you);assert.equal(result.data.game.key,initial.game.key);assert.deepEqual(result.data.game.worms.map(w=>w.hp),initial.game.worms.map(w=>w.hp));});
test('four-team match and tournament create separate authoritative games',async()=>{for(const kind of ['duel','tournament']){const {players,root}=await match(4,kind);const r=(await players[0].req(root+'/sync')).data;assert.equal(r.room.players.length,4);assert.equal(r.room.matches.length,kind==='duel'?1:2);assert.equal(r.game.teams.length,kind==='duel'?4:2);}});
test('unknown membership rejected; no auth cookie visible in room JSON',async()=>{const {actor,players,root}=await match();assert.equal((await client(actor).req(root+'/sync')).status,401);const r=await players[0].req(root+'/sync');assert.ok(r.data.room.players.every(p=>!('token'in p)));});
test('origin and malformed payload rejected',async()=>{const a=new GameAuthority(context(),{});const res=await a.fetch(new Request(origin+'/api/rooms',{method:'POST',headers:{'content-type':'application/json',origin:'https://elsewhere.example'},body:'{}'}));assert.equal(res.status,403);const large=await a.fetch(new Request(origin+'/api/rooms',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'x'.repeat(8500)})}));assert.equal(large.status,413);});
